
server:
  port: 8082



spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost/chat_memory_db

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${spring.datasource.password}

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${langchain4j.community.dashscope.chat-model.api-key}
        model-name: qwen-max
